version: "3.9"

name: cashflow_mvp

services:
  app:
    build: .
    container_name: cashflow_app
    ports:
      - "8080:80"
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=${APP_URL:-http://localhost:8080}
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-cashflow}
      - MYSQL_USER=${MYSQL_USER:-cashflow}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-cashflow}
      - MYSQL_PORT=3306
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: bash -lc "/usr/local/bin/entrypoint.sh"

  db:
    image: mysql:8.0
    container_name: cashflow_db
    ports:
      - "${EXTERNAL_MYSQL_PORT:-3307}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-cashflow}
      - MYSQL_USER=${MYSQL_USER:-cashflow}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-cashflow}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  db_data:



